/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/setsMappers";
import * as Parameters from "../models/parameters";
import { ScryfallClientContext } from "../scryfallClientContext";

/** Class representing a Sets. */
export class Sets {
  private readonly client: ScryfallClientContext;

  /**
   * Create a Sets.
   * @param {ScryfallClientContext} client Reference to the service client.
   */
  constructor(client: ScryfallClientContext) {
    this.client = client;
  }

  /**
   * @param {RequestOptionsBase} [options] Optional Parameters.
   *
   * @returns {Promise} A promise is returned
   *
   * @resolve {HttpOperationResponse} The deserialized result object.
   *
   * @reject {Error|ServiceError} The error object.
   */
  getAllWithHttpOperationResponse(options?: msRest.RequestOptionsBase): Promise<msRest.HttpOperationResponse<Models.SetList>> {
    return this.client.sendOperationRequest(
      {
        options
      },
      getAllOperationSpec);
  }

  /**
   * @param {string} code
   *
   * @param {RequestOptionsBase} [options] Optional Parameters.
   *
   * @returns {Promise} A promise is returned
   *
   * @resolve {HttpOperationResponse} The deserialized result object.
   *
   * @reject {Error|ServiceError} The error object.
   */
  getByCodeWithHttpOperationResponse(code: string, options?: msRest.RequestOptionsBase): Promise<msRest.HttpOperationResponse<Models.Set>> {
    return this.client.sendOperationRequest(
      {
        code,
        options
      },
      getByCodeOperationSpec);
  }

  /**
   * @param {RequestOptionsBase} [options] Optional Parameters.
   *
   * @param {ServiceCallback} callback The callback.
   *
   * @returns {ServiceCallback} callback(err, result, request, operationRes)
   *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
   *                      {Models.SetList} [result]   - The deserialized result object if an error did not occur.
   *                      See {@link Models.SetList} for more information.
   *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
   *                      {HttpOperationResponse} [response] - The HTTP Response stream if an error did not occur.
   */
  getAll(): Promise<Models.SetList>;
  getAll(options: msRest.RequestOptionsBase): Promise<Models.SetList>;
  getAll(callback: msRest.ServiceCallback<Models.SetList>): void;
  getAll(options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.SetList>): void;
  getAll(options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<Models.SetList>): any {
    return msRest.responseToBody(this.getAllWithHttpOperationResponse.bind(this), options, callback);
  }

  /**
   * @param {string} code
   *
   * @param {RequestOptionsBase} [options] Optional Parameters.
   *
   * @param {ServiceCallback} callback The callback.
   *
   * @returns {ServiceCallback} callback(err, result, request, operationRes)
   *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
   *                      {Models.Set} [result]   - The deserialized result object if an error did not occur.
   *                      See {@link Models.Set} for more information.
   *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
   *                      {HttpOperationResponse} [response] - The HTTP Response stream if an error did not occur.
   */
  getByCode(code: string): Promise<Models.Set>;
  getByCode(code: string, options: msRest.RequestOptionsBase): Promise<Models.Set>;
  getByCode(code: string, callback: msRest.ServiceCallback<Models.Set>): void;
  getByCode(code: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.Set>): void;
  getByCode(code: string, options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<Models.Set>): any {
    return msRest.responseToBody(this.getByCodeWithHttpOperationResponse.bind(this), code, options, callback);
  }

}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const getAllOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "sets",
  responses: {
    200: {
      bodyMapper: Mappers.SetList
    },
    default: {
      bodyMapper: Mappers.ErrorModel
    }
  },
  serializer
};

const getByCodeOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "sets/{code}",
  urlParameters: [
    Parameters.code
  ],
  responses: {
    200: {
      bodyMapper: Mappers.Set
    },
    default: {
      bodyMapper: Mappers.ErrorModel
    }
  },
  serializer
};
