/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const code: msRest.OperationURLParameter = {
  parameterPath: "code",
  mapper: {
    required: true,
    serializedName: "code",
    type: {
      name: "String"
    }
  }
};
export const cost: msRest.OperationQueryParameter = {
  parameterPath: "cost",
  mapper: {
    required: true,
    serializedName: "cost",
    type: {
      name: "String"
    }
  }
};
export const dir: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "dir"
  ],
  mapper: {
    serializedName: "dir",
    type: {
      name: "Enum",
      allowedValues: [
        "auto",
        "asc",
        "desc"
      ]
    }
  }
};
export const exact: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "exact"
  ],
  mapper: {
    serializedName: "exact",
    type: {
      name: "String"
    }
  }
};
export const face: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "face"
  ],
  mapper: {
    serializedName: "face",
    type: {
      name: "String"
    }
  }
};
export const format: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "format"
  ],
  mapper: {
    serializedName: "format",
    type: {
      name: "String"
    }
  }
};
export const fuzzy: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "fuzzy"
  ],
  mapper: {
    serializedName: "fuzzy",
    type: {
      name: "String"
    }
  }
};
export const id0: msRest.OperationURLParameter = {
  parameterPath: "id",
  mapper: {
    required: true,
    serializedName: "id",
    type: {
      name: "Number"
    }
  }
};
export const id1: msRest.OperationURLParameter = {
  parameterPath: "id",
  mapper: {
    required: true,
    serializedName: "id",
    type: {
      name: "Uuid"
    }
  }
};
export const includeExtras: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "includeExtras"
  ],
  mapper: {
    serializedName: "include_extras",
    type: {
      name: "Boolean"
    }
  }
};
export const number: msRest.OperationURLParameter = {
  parameterPath: "number",
  mapper: {
    required: true,
    serializedName: "number",
    type: {
      name: "Number"
    }
  }
};
export const order: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "order"
  ],
  mapper: {
    serializedName: "order",
    type: {
      name: "Enum",
      allowedValues: [
        "name",
        "set",
        "released",
        "rarity",
        "color",
        "usd",
        "tix",
        "eur",
        "cmc",
        "power",
        "toughness",
        "edhrec",
        "artist"
      ]
    }
  }
};
export const page: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "page"
  ],
  mapper: {
    serializedName: "page",
    type: {
      name: "Number"
    }
  }
};
export const pretty: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "pretty"
  ],
  mapper: {
    serializedName: "pretty",
    type: {
      name: "Boolean"
    }
  }
};
export const q: msRest.OperationQueryParameter = {
  parameterPath: "q",
  mapper: {
    required: true,
    serializedName: "q",
    type: {
      name: "String"
    }
  }
};
export const set: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "set"
  ],
  mapper: {
    serializedName: "set",
    type: {
      name: "String"
    }
  }
};
export const unique: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "unique"
  ],
  mapper: {
    serializedName: "unique",
    type: {
      name: "Enum",
      allowedValues: [
        "cards",
        "art",
        "prints"
      ]
    }
  }
};
export const version: msRest.OperationQueryParameter = {
  parameterPath: [
    "options",
    "version"
  ],
  mapper: {
    serializedName: "version",
    type: {
      name: "String"
    }
  }
};
