/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { ScryfallClientContext } from "./scryfallClientContext";

class ScryfallClient extends ScryfallClientContext {
  // Operation groups
  sets: operations.Sets;
  cards: operations.Cards;
  rulings: operations.Rulings;
  symbology: operations.Symbology;
  catalog: operations.CatalogOperations;

  /**
   * Initializes a new instance of the ScryfallClient class.
   * @param [options] The parameter options
   */
  constructor(options?: Models.ScryfallClientOptions) {
    super(options);
    this.sets = new operations.Sets(this);
    this.cards = new operations.Cards(this);
    this.rulings = new operations.Rulings(this);
    this.symbology = new operations.Symbology(this);
    this.catalog = new operations.CatalogOperations(this);
  }
}

// Operation Specifications

export {
  ScryfallClient,
  ScryfallClientContext,
  Models as ScryfallModels,
  Mappers as ScryfallMappers
};
export * from "./operations";
